name: 'pkmn_yellow_legacy_map'
version: '1.0.0'
profile: 'pkmn_yellow_legacy_map'

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ drop_dbt_loaded_at_col() }}"

on-run-end:
  - "{{ add_dbt_loaded_at_col() }}"

seeds:
  +delimiter: ','
  +schema: raw

models:
  pkmn_yellow_legacy_map:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    optimisation:
      +materialized: table
      +schema: optimisation